apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}
    database: ${DATABASE}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: false
    jsonData:
      sslmode: "disable"

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: ${TIMESCALE_HOST_NAME}
    database: ${TIMESCALE_DATABASE}
    user: ${TIMESCALE_USER}
    secureJsonData:
      password: ${TIMESCALE_PASSWORD}
    isDefault: false
    jsonData:
      sslmode: "disable"

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://backtest:5000
    isDefault: false
    editable: true
